version: '3.7'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkinsDockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    privileged: true
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
